services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ai-analysis-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
