
services:
  db:
    image: postgres:15
    container_name: survey_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: surveys
    volumes:
      - db_data:/var/lib/postgresql/data
    command: > 
      bash -c "
        set -e;
        apt-get update && \
        apt-get install -y postgresql-server-dev-15 build-essential && \
        pgxn install vector && \
        mkdir -p /docker-entrypoint-initdb.d && \
        echo \"CREATE EXTENSION IF NOT EXISTS vector;\" > /docker-entrypoint-initdb.d/pgvector.sql && \
        exec docker-entrypoint.sh postgres
      "
    ports:
      - '5432:5432'